### ISSUE TITLE
about Requirements

### ISSUE THREAD

**Issue by Ai-is-light** [okankop/MFF-pytorch#3]
Tanks for your good work.
but, I would to like to know more details about the requirements, like the pytorch's version. And you said ,OpenCV compiled with CUDA and FFmpeg, for optical flow calculation and data augmentations, which means that the opencv must complied with CUDA and FFmpeg?? How about pip install python-opencv
@okankop

**Comment by okankop** [comment]
The code is tested with Python 3.6 and torch 0.3.1. For data augmentation, you do not need to CUDA compiled OpenCV. You can simply use `pip install opencv-python` (or for anaconda environment `conda install -c conda-forge opencv` ) . However, in order to use the code in https://github.com/okankop/flow_computation for optical flow extraction, OpenCV should be compiled with CUDA.
